#ifndef MULTICAST_CONST_H_
#define MULTICAST_CONST_H_

#define MULTICAST_GROUP     "224.0.0.37"
#define MULTICAST_PORT_LISTEN_ON_PJSUA_APP     6060
#define MULTICAST_PORT_LISTEN_ON_EXTERNAL_APP  6061
#define MULTICAST_IP_IFACE  "127.0.0.1"



#endif // MULTICAST_CONST_H_
